#pragma once

// 控制arx模块的加载
#define INCLUDE_VENT_MODULE 1

#define INCLUDE_TVNS_MODULE 1

#define INCLUDE_EVAL_MODULE 0

#define INCLUDE_GAS_MODULE 0

#define INCLUDE_VNC_MODULE 0

#define INCLUDE_MVSS_MODULE 0

#define INCLUDE_VNG_GEN_MODULE 0

#define INCLUDE_TEST_MODULE 0

#define INCLUDE_FFC_MODULE 0

#define INCLUDE_GESES_MODULE 1

// 全局浮点数精度
// 主要用于几何坐标判断
#define GLOBAL_TOLERANCE 1e-5