#pragma once

#define PERMENT_OBJCT_NAME	_T("地面永久瓦斯抽放系统")
#define TEMPGAS_OBJCT_NAME	_T("井下移动瓦斯抽放系统")
#define GAS_PUMP_OBJCT_NAME	_T("瓦斯抽采泵站能力")
#define RUNNING_SYS_OBJCT_NAME	_T("正常运转的系统名称")
#define GAS_PLAN_BOOKMKS_OBJCT_NAME	_T("年度计划书签")
#define INSPECT_BOOKMKS_OBJCT_NAME	_T("竣工验收书签")
#define SM_BOOKMKS_OBJCT_NAME	_T("自我评价和管理书签")
#define EPCMFD_BOOKMKS_OBJCT_NAME	_T("抽采方案和采掘面设计书签")

#define RET_GASSYS_OBJCT_NAME	_T("瓦斯抽采系统达标评判")
#define RET_EPCMFD_OBJCT_NAME	_T("抽采方案和采掘面施工设计")
#define RET_GASPLAN_OBJCT_NAME	_T("抽采规划和年度计划")
#define RET_INSPECT_OBJCT_NAME	_T("瓦斯抽采工程验收资料")
#define RET_SM_OBJCT_NAME	_T("自我评价体系和管理制度")
#define RET_GASPUMP_OBJCT_NAME	_T("泵站能力和备用泵站能力")
#define RET_MERSURE_OBJCT_NAME	_T("计量测点、计量器评判")
#define RET_REALATE_OBJCT_NAME	_T("抽采效果相关资料评判")

#define DESC_GASSYS_OBJCT_NAME	_T("瓦斯抽采系统达标评判描述")
#define DESC_EPCMFD_OBJCT_NAME	_T("抽采方案和采掘面施工设计描述")
#define DESC_GASPLAN_OBJCT_NAME	_T("抽采规划和年度计划描述")
#define DESC_INSPECT_OBJCT_NAME	_T("瓦斯抽采工程验收资料描述")
#define DESC_SM_OBJCT_NAME	_T("自我评价体系和管理制度描述")
#define DESC_GASPUMP_OBJCT_NAME	_T("泵站能力和备用泵站能力描述")
